version: '3.1'
services:
  backend:
    container_name: flask
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - FLASK_APP=run.py
      - FLASK_DEBUG=1
    ports:
      - "80:3000"
    volumes:
      - .:/usr/src/
    networks:
      - flask-net
    user: "1000"
  
  db:
    image: mysql:8.0
    container_name: flask-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: users
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - flask_database_volume:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - flask-net

networks:
  flask-net:
    name: flask-network
volumes:
  flask_database_volume: